Repository Chaeyeon1/sui, pull requests merged in 2023-07, with the labels that each got.

#27 ✨Toast 컴포넌트 contained 개발
  src/components/Toast/Toast.stories.tsx
  src/components/Toast/Toast.tsx
  src/components/Toast/index.ts
  src/components/chip/Chip.stories.tsx
  src/components/chip/Chip.tsx
  tailwind.config.js
Labels: 컴포넌트 추가, 수연, 토스트

#28 ✨Toast 컴포넌트 outlined 개발
  src/components/Toast/Toast.stories.tsx
  src/components/Toast/Toast.tsx
Labels: 컴포넌트 추가, 수연, 토스트

#32 ✨ Menu 컴포넌트 개발
  src/assets/star.svg
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/Accorion.stories.tsx
  src/components/Layout.tsx
  src/components/Menu/Menu.stories.tsx
  src/components/Menu/Menu.style.ts
  src/components/Menu/Menu.tsx
  src/components/Menu/Menu.type.ts
  src/components/Menu/index.ts
  src/components/util/commonStyle.ts
  src/svg.d.ts
  tsconfig.json
Labels: 컴포넌트 추가, 채연, 메뉴

#39 🎨Button, Chip, Textfield, Toast component code refactoring
  src/assets/error.svg
  src/assets/info.svg
  src/assets/success.svg
  src/assets/warning.svg
  src/components/Accordion/Accordion.style.ts
  src/components/Accordion/Accordion.tsx
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.style.ts
  src/components/Button/Button.tsx
  src/components/Button/Button.type.ts
  src/components/Chip/Chip.style.ts
  src/components/Chip/Chip.type.ts
  src/components/TextField/TextField.stories.tsx
  src/components/TextField/TextField.style.ts
  src/components/TextField/TextField.tsx
  src/components/TextField/TextField.type.ts
  src/components/Toast/Toast.stories.tsx
  src/components/Toast/Toast.style.ts
  src/components/Toast/Toast.tsx
  src/components/Toast/Toast.type.ts
  src/components/chip/Chip.stories.tsx
  src/components/chip/Chip.tsx
Labels: 코드 개선, 텍스트 필드, 버튼, 수연, 칩, 토스트

#40 ✨switch 컴포넌트 개발
  src/components/Dialog/Dialog.stories.tsx
  src/components/Dialog/Dialog.tsx
  src/components/Dialog/index.ts
  src/components/Switch/Switch.stories.tsx
  src/components/Switch/Switch.style.ts
  src/components/Switch/Switch.tsx
  src/components/Switch/Switch.type.ts
  src/components/Switch/index.ts
Labels: 컴포넌트 추가, 수연, 스위치

#48 🎨 storybook layout에 맞춰서 정리
  src/components/Select/Select.stories.tsx
  src/components/Select/Select.style.ts
  src/components/Select/Select.tsx
Labels: 컴포넌트 수정, 째째, 셀렉트

#30 ✨Dialog 컴포넌트 개발
  package.json
  src/components/Dialog/Dialog.stories.tsx
  src/components/Dialog/Dialog.styles.ts
  src/components/Dialog/Dialog.tsx
  src/components/Dialog/Dialog.type.ts
  src/components/TextField/TextField.stories.tsx
  src/components/Toast/Toast.stories.tsx
  src/components/chip/Chip.stories.tsx
Labels: 컴포넌트 추가, 수연, 다이얼로그
