Repository Chaeyeon1/sui, pull requests merged in 2023-06, with the labels that each got.

#2 ✨ Typescript + Tailwind + Storybook 초기 설정
  .babelrc.json
  .gitattributes
  .gitignore
  .prettierignore
  .prettierrc.js
  .storybook/main.js
  .storybook/main.ts
  .storybook/preview-head.html
  .storybook/preview.js
  .storybook/preview.ts
  README.md
  assets/buttons.png
  package-lock.json
  package.json
  postcss.config.js
  public/fonts/Inter-italic.var.woff2
  public/fonts/Inter-roman.var.woff2
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.tsx
  src/components/Button/index.ts
  src/components/index.ts
  src/index.ts
  src/styles/fonts.css
  src/styles/tailwind.css
  stories/Button.stories.ts
  stories/Button.tsx
  stories/assets/code-brackets.svg
  stories/assets/colors.svg
  stories/assets/comments.svg
  stories/assets/direction.svg
  stories/assets/flow.svg
  stories/assets/plugin.svg
  stories/assets/repo.svg
  stories/assets/stackalt.svg
  stories/button.css
  tailwind.config.js
  tsconfig.json
Labels: 채연, 초기 설정

#5 ✨ 스토리북 배포 및 Craco 설치
  .storybook/main.js
  build-storybook.log
  craco.config.js
  package-lock.json
  package.json
  src/components/Button/Button.tsx
  tailwind.config.js
Labels: 채연, 초기 설정

#7 ✨ 버튼 컴포넌트 개발
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.tsx
Labels: 컴포넌트 추가, 버튼, 채연, 수연

#12 ✨ Accordion Summary 컴포넌트 구현
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/Accorion.stories.tsx
  src/components/Accordion/expandLess.svg
  src/components/Accordion/expandMore.svg
  src/components/Accordion/index.ts
Labels: 컴포넌트 추가, 채연, 아코디언

#13 ✨textfield outlined 개발
  src/components/TextField/TextField.stories.tsx
  src/components/TextField/TextField.tsx
  src/components/TextField/index.ts
Labels: 컴포넌트 추가, 텍스트 필드, 수연

#17 ✨ accordion summary 컴포넌트 개발
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/Accorion.stories.tsx
Labels: 컴포넌트 추가, 채연, 아코디언

#19 ✨chip outlined 컴포넌트 개발
  src/components/chip/Chip.stories.tsx
  src/components/chip/Chip.tsx
Labels: 컴포넌트 추가, 수연, 칩

#20 ✨chip contained 컴포넌트 개발
  src/components/chip/Chip.stories.tsx
  src/components/chip/Chip.tsx
  src/components/chip/index.ts
Labels: 컴포넌트 추가, 수연, 칩

#22 🎨 불필요한 코드 삭제
  src/components/TextField/TextField.stories.tsx
  src/components/chip/Chip.tsx
Labels: 코드 개선, 칩

#25 🎨 accordion 수정사항 반영
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/Accorion.stories.tsx
Labels: 컴포넌트 수정, 채연, 아코디언
